### ISSUE TITLE
Unable to start clockwork as a daemon

### ISSUE THREAD

**Issue by sangamgupta85** [tomykaira/clockwork#159]
Hi there

I am using Rails 4.2.1,  Ruby 2.1.4 and clockwork 1.2.0. I have a clockwork.rb file inside lib directory as follows.

require 'clockwork'
require './config/boot'
require './config/environment'

include Clockwork
every(1.week,'weekly_worker called', :at => 'Sunday 11:45', :tz => 'UTC') { WeeklyWorker.perform_async }

When I run the command:
clockworkd -c lib/clock.rb start -l

I get the following error inside clockworkd.clock.output

from /usr/local/rvm/gems/ruby-2.1.4@the-exchange-app/gems/daemons-1.2.3/lib/daemons/application.rb:269:in `start_proc'
	from /usr/local/rvm/gems/ruby-2.1.4@the-exchange-app/gems/daemons-1.2.3/lib/daemons/application.rb:295:in `start'
	from /usr/local/rvm/gems/ruby-2.1.4@the-exchange-app/gems/daemons-1.2.3/lib/daemons/controller.rb:56:in `run'
	from /usr/local/rvm/gems/ruby-2.1.4@the-exchange-app/gems/daemons-1.2.3/lib/daemons.rb:193:in `block in run_proc'
	from /usr/local/rvm/gems/ruby-2.1.4@the-exchange-app/gems/daemons-1.2.3/lib/daemons/cmdline.rb:88:in `call'
	from /usr/local/rvm/gems/ruby-2.1.4@the-exchange-app/gems/daemons-1.2.3/lib/daemons/cmdline.rb:88:in `catch_exceptions'
	from /usr/local/rvm/gems/ruby-2.1.4@the-exchange-app/gems/daemons-1.2.3/lib/daemons.rb:192:in `run_proc'
	from /usr/local/rvm/gems/ruby-2.1.4@the-exchange-app/gems/clockwork-1.2.0/bin/clockworkd:84:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.4@the-exchange-app/bin/clockworkd:23:in `load'
	from /usr/local/rvm/gems/ruby-2.1.4@the-exchange-app/bin/clockworkd:23:in `<main>'

Has someone faced this issue before? Any help would be appreciated.

Thanks
Sangam Gupta

**Comment by sangamgupta85** [comment]
Waiting for an update please?
